name: Check python 
on:
  pull_request: {}
  # push: { branches: [main] }

jobs:
  job:
    name: Check python 
    runs-on: ubuntu-latest
    steps:
      - name: Check python 
        run: |
          python3 -V
